alias ack='ack-grep'
alias rs='rails server thin'
alias ri='ri --no-pager'
alias rsl='DELIVER_LETTERS=1 rails server thin'
alias most-used-cli='history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | sort -rn | head'
